## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
from re import A
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df=application_df.drop(['EIN','NAME'],axis=1)

In [ ]:
# Determine the number of unique values in each column.
unique_value_counts = application_df.nunique()
print(unique_value_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
value_counts = application_df['APPLICATION_TYPE'].value_counts()
print(value_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value=500
application_types_to_replace = value_counts[value_counts < cutoff_value].index
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
value_counts=application_df['CLASSIFICATION'].value_counts()
print(value_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
value_counts[value_counts > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value=1000
classifications_to_replace = value_counts[value_counts < cutoff_value].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)

In [ ]:
# Split our preprocessed data into our features and target arrays
#features
X = application_df.drop('IS_SUCCESSFUL', axis=1)
#target arrays
y = application_df['IS_SUCCESSFUL'].values
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42,stratify=y)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
nn = tf.keras.models.Sequential()

# First hidden layer with all the features
nn.add(tf.keras.layers.Dense(units=80, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=50, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 80)                  │           3,520 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 50)                  │           4,050 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 30)                  │           1,530 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1)                   │              31 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9,131 (35.67 KB)

 Trainable params: 9,131 (35.67 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7084 - loss: 0.5856
Epoch 2/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7292 - loss: 0.5596
Epoch 3/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7318 - loss: 0.5516
Epoch 4/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7304 - loss: 0.5523
Epoch 5/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7337 - loss: 0.5476
Epoch 6/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7348 - loss: 0.5455
Epoch 7/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7321 - loss: 0.5465
Epoch 8/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7301 - loss: 0.5484
Epoch 9/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7360 - loss: 0.5423
Epoch 10/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7314 - loss: 0.5523
Epoch 11/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7378 - loss: 0.5433
Epoch 12/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7402 - loss: 0.5371
Epoch 13/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7344 - loss: 0.5429
Epoch 14/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7386 - loss: 0.5418
Epoch 15/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7413 - loss: 0.5386
Epoch 16/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7356 - loss: 0.5437
Epoch 17/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7405 - loss: 0.5380
Epoch 18/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7382 - loss: 0.5400
Epoch 19/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7366 - loss: 0.5400
Epoch 20/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7421 - loss: 0.5357
Epoch 21/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7366 - loss: 0.5429
Epoch 22/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7363 - loss: 0.5434
Epoch 23/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7394 - loss: 0.5400
Epoch 24/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7375 - loss: 0.5424
Epoch 25/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7380 - loss: 0.5400
Epoch 26/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7399 - loss: 0.5372
Epoch 27/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7408 - loss: 0.5353
Epoch 28/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7400 - loss: 0.5392
Epoch 29/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7427 - loss: 0.5351
Epoch 30/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7384 - loss: 0.5408
Epoch 31/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7377 - loss: 0.5414
Epoch 32/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7393 - loss: 0.5357
Epoch 33/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7358 - loss: 0.5429
Epoch 34/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7436 - loss: 0.5348
Epoch 35/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7397 - loss: 0.5366
Epoch 36/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7394 - loss: 0.5405
Epoch 37/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7357 - loss: 0.5440
Epoch 38/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7427 - loss: 0.5347
Epoch 39/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7380 - loss: 0.5370
Epoch 40/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7380 - loss: 0.5389
Epoch 41/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7355 - loss: 0.5410
Epoch 42/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7443 - loss: 0.5308
Epoch 43/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7420 - loss: 0.5362
Epoch 44/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7410 - loss: 0.5357
Epoch 45/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7438 - loss: 0.5354
Epoch 46/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7419 - loss: 0.5338
Epoch 47/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7416 - loss: 0.5344
Epoch 48/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7453 - loss: 0.5305
Epoch 49/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7433 - loss: 0.5330
Epoch 50/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7362 - loss: 0.5398

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 2ms/step - accuracy: 0.7258 - loss: 0.5573
Loss: 0.557338297367096, Accuracy: 0.7258309125900269

# Variance Inflation Factor (VIF)

In [ ]:
#check the data types
print(X_train.dtypes)

STATUS                          int64
ASK_AMT                         int64
APPLICATION_TYPE_Other           bool
APPLICATION_TYPE_T10             bool
APPLICATION_TYPE_T19             bool
APPLICATION_TYPE_T3              bool
APPLICATION_TYPE_T4              bool
APPLICATION_TYPE_T5              bool
APPLICATION_TYPE_T6              bool
APPLICATION_TYPE_T7              bool
APPLICATION_TYPE_T8              bool
AFFILIATION_CompanySponsored     bool
AFFILIATION_Family/Parent        bool
AFFILIATION_Independent          bool
AFFILIATION_National             bool
AFFILIATION_Other                bool
AFFILIATION_Regional             bool
CLASSIFICATION_C1000             bool
CLASSIFICATION_C1200             bool
CLASSIFICATION_C2000             bool
CLASSIFICATION_C2100             bool
CLASSIFICATION_C3000             bool
CLASSIFICATION_Other             bool
USE_CASE_CommunityServ           bool
USE_CASE_Heathcare               bool
USE_CASE_Other                   bool
USE_CASE_Preservation            bool
USE_CASE_ProductDev              bool
ORGANIZATION_Association         bool
ORGANIZATION_Co-operative        bool
ORGANIZATION_Corporation         bool
ORGANIZATION_Trust               bool
INCOME_AMT_0                     bool
INCOME_AMT_1-9999                bool
INCOME_AMT_10000-24999           bool
INCOME_AMT_100000-499999         bool
INCOME_AMT_10M-50M               bool
INCOME_AMT_1M-5M                 bool
INCOME_AMT_25000-99999           bool
INCOME_AMT_50M+                  bool
INCOME_AMT_5M-10M                bool
SPECIAL_CONSIDERATIONS_N         bool
SPECIAL_CONSIDERATIONS_Y         bool
dtype: object

In [ ]:
# Clean the X_train data set
# Drop the null values
X_train = X_train.fillna(0)
# Convert all boolean columns to int64
X_train = X_train.astype(int)
print(X_train.dtypes)

STATUS                          int64
ASK_AMT                         int64
APPLICATION_TYPE_Other          int64
APPLICATION_TYPE_T10            int64
APPLICATION_TYPE_T19            int64
APPLICATION_TYPE_T3             int64
APPLICATION_TYPE_T4             int64
APPLICATION_TYPE_T5             int64
APPLICATION_TYPE_T6             int64
APPLICATION_TYPE_T7             int64
APPLICATION_TYPE_T8             int64
AFFILIATION_CompanySponsored    int64
AFFILIATION_Family/Parent       int64
AFFILIATION_Independent         int64
AFFILIATION_National            int64
AFFILIATION_Other               int64
AFFILIATION_Regional            int64
CLASSIFICATION_C1000            int64
CLASSIFICATION_C1200            int64
CLASSIFICATION_C2000            int64
CLASSIFICATION_C2100            int64
CLASSIFICATION_C3000            int64
CLASSIFICATION_Other            int64
USE_CASE_CommunityServ          int64
USE_CASE_Heathcare              int64
USE_CASE_Other                  int64
USE_CASE_Preservation           int64
USE_CASE_ProductDev             int64
ORGANIZATION_Association        int64
ORGANIZATION_Co-operative       int64
ORGANIZATION_Corporation        int64
ORGANIZATION_Trust              int64
INCOME_AMT_0                    int64
INCOME_AMT_1-9999               int64
INCOME_AMT_10000-24999          int64
INCOME_AMT_100000-499999        int64
INCOME_AMT_10M-50M              int64
INCOME_AMT_1M-5M                int64
INCOME_AMT_25000-99999          int64
INCOME_AMT_50M+                 int64
INCOME_AMT_5M-10M               int64
SPECIAL_CONSIDERATIONS_N        int64
SPECIAL_CONSIDERATIONS_Y        int64
dtype: object

In [ ]:
# Check the multicollinearity:

# Check the multicollinearity:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_data = pd.DataFrame()
vif_data["feature"] = X_train.columns
vif_data["VIF"] = [variance_inflation_factor(X_train.values, i) for i in range(X_train.shape[1])]

print(vif_data)

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

                         feature           VIF
0                         STATUS  1.002545e+00
1                        ASK_AMT  1.246992e+00
2         APPLICATION_TYPE_Other           inf
3           APPLICATION_TYPE_T10           inf
4           APPLICATION_TYPE_T19           inf
5            APPLICATION_TYPE_T3  3.602880e+14
6            APPLICATION_TYPE_T4           inf
7            APPLICATION_TYPE_T5           inf
8            APPLICATION_TYPE_T6           inf
9            APPLICATION_TYPE_T7           inf
10           APPLICATION_TYPE_T8           inf
11  AFFILIATION_CompanySponsored           inf
12     AFFILIATION_Family/Parent           inf
13       AFFILIATION_Independent           inf
14          AFFILIATION_National           inf
15             AFFILIATION_Other           inf
16          AFFILIATION_Regional           inf
17          CLASSIFICATION_C1000  7.505999e+14
18          CLASSIFICATION_C1200           inf
19          CLASSIFICATION_C2000           inf
20          CLASSIFICATION_C2100           inf
21          CLASSIFICATION_C3000           inf
22          CLASSIFICATION_Other           inf
23        USE_CASE_CommunityServ           inf
24            USE_CASE_Heathcare           inf
25                USE_CASE_Other           inf
26         USE_CASE_Preservation           inf
27           USE_CASE_ProductDev  3.336000e+14
28      ORGANIZATION_Association           inf
29     ORGANIZATION_Co-operative           inf
30      ORGANIZATION_Corporation           inf
31            ORGANIZATION_Trust           inf
32                  INCOME_AMT_0           inf
33             INCOME_AMT_1-9999           inf
34        INCOME_AMT_10000-24999           inf
35      INCOME_AMT_100000-499999           inf
36            INCOME_AMT_10M-50M           inf
37              INCOME_AMT_1M-5M  9.007199e+15
38        INCOME_AMT_25000-99999  9.007199e+15
39               INCOME_AMT_50M+           inf
40             INCOME_AMT_5M-10M           inf
41      SPECIAL_CONSIDERATIONS_N  6.127346e+13
42      SPECIAL_CONSIDERATIONS_Y           inf

In [ ]:
correlation_matrix = application_df.corr()
status_correlation = correlation_matrix['STATUS'].abs()
print(status_correlation)

STATUS                          1.000000
ASK_AMT                         0.000383
IS_SUCCESSFUL                   0.001636
APPLICATION_TYPE_Other          0.001088
APPLICATION_TYPE_T10            0.001510
APPLICATION_TYPE_T19            0.002162
APPLICATION_TYPE_T3             0.006258
APPLICATION_TYPE_T4             0.002620
APPLICATION_TYPE_T5             0.002272
APPLICATION_TYPE_T6             0.002315
APPLICATION_TYPE_T7             0.001774
APPLICATION_TYPE_T8             0.001789
AFFILIATION_CompanySponsored    0.001403
AFFILIATION_Family/Parent       0.000522
AFFILIATION_Independent         0.001483
AFFILIATION_National            0.000375
AFFILIATION_Other               0.000130
AFFILIATION_Regional            0.000235
CLASSIFICATION_C1000            0.002291
CLASSIFICATION_C1200            0.004893
CLASSIFICATION_C2000            0.000725
CLASSIFICATION_C2100            0.007692
CLASSIFICATION_C3000            0.002939
CLASSIFICATION_Other            0.003208
USE_CASE_CommunityServ          0.044620
USE_CASE_Heathcare              0.000789
USE_CASE_Other                  0.000113
USE_CASE_Preservation           0.006874
USE_CASE_ProductDev             0.005374
ORGANIZATION_Association        0.002664
ORGANIZATION_Co-operative       0.001448
ORGANIZATION_Corporation        0.000428
ORGANIZATION_Trust              0.002226
INCOME_AMT_0                    0.002958
INCOME_AMT_1-9999               0.001778
INCOME_AMT_10000-24999          0.017815
INCOME_AMT_100000-499999        0.003988
INCOME_AMT_10M-50M              0.001014
INCOME_AMT_1M-5M                0.002043
INCOME_AMT_25000-99999          0.003513
INCOME_AMT_50M+                 0.000770
INCOME_AMT_5M-10M               0.000889
SPECIAL_CONSIDERATIONS_N        0.085768
SPECIAL_CONSIDERATIONS_Y        0.085768
Name: STATUS, dtype: float64

In [ ]:
# Export our model to HDF5 file
nn.save("initial_model.h5")